# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchants',
            name='posnumber',
        ),
        migrations.AlterField(
            model_name='merchants',
            name='name',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name'),
        ),
    ]
