# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20160824_1339'),
        ('students', '0003_auto_20160823_1230'),
        ('pos_portal', '0002_auto_20160820_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(default='', max_length=10000)),
                ('encryped_acc_no', models.CharField(max_length=10000)),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank name')),
                ('expirerydate', models.DateField(verbose_name='expirerydate')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name')),
                ('studentprofiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles')),
            ],
            options={
                'verbose_name_plural': 'StudentAccounts',
            },
        ),
        migrations.CreateModel(
            name='StudentAccountsWallets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletname_name', models.CharField(max_length=255, verbose_name='Bank name')),
                ('max_amount', models.IntegerField(verbose_name='Max amount')),
                ('opendate', models.DateField(verbose_name='Admission Date')),
                ('bank_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_portal.StudentAccounts', verbose_name='Bank Acc')),
            ],
            options={
                'verbose_name_plural': 'Student Bank Acc',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=10000)),
                ('amount', models.CharField(max_length=10000)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('trace_no', models.CharField(max_length=10000)),
                ('ref_no', models.CharField(max_length=10000)),
                ('currency', models.CharField(max_length=10000)),
                ('location', models.CharField(max_length=10000)),
                ('terminal_id', models.CharField(max_length=10000)),
                ('studentaccounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_portal.StudentAccounts')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos_portal.StudentAccountsWallets')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
