# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0003_studentaccounts_studentaccountswallets_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='terminal_id',
        ),
        migrations.AddField(
            model_name='transactions',
            name='terminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pos_portal.Pos'),
        ),
    ]
