# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0007_pos_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='balance',
        ),
        migrations.AddField(
            model_name='transactions',
            name='balance',
            field=models.CharField(default=100, max_length=5000),
        ),
        migrations.AddField(
            model_name='transactions',
            name='reverse',
            field=models.CharField(default=100, max_length=5000),
        ),
    ]
