# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0008_auto_20160826_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccounts',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='studentaccounts',
            name='name',
        ),
    ]
