# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0011_auto_20160826_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name'),
        ),
    ]
