# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0012_auto_20160826_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccountswallets',
            name='walletname_name',
            field=models.CharField(max_length=255),
        ),
    ]
