# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0013_auto_20160902_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchants',
            name='balance',
            field=models.CharField(default=10300, max_length=5000),
        ),
    ]
