# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_portal', '0015_auto_20161004_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='ref_no',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trace_no',
            field=models.CharField(max_length=10000),
        ),
    ]
