"""
Django settings for ecoins project.

Generated by 'django-admin startproject' using Django 1.9.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ra6eerd2&we+#u@d$$s-#r3e-3)#(-9y3kro+b0nofixnvuh^4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'theme.apps.ThemeConfig',
    #'system_settings.apps.SystemSettingsConfig',
    'frontend.apps.FrontendConfig',
    'login.apps.LoginConfig',
    'staff.apps.StaffConfig',
		'smsgateway.apps.SmsgatewayConfig',
    'school.apps.SchoolConfig',
    'pos_portal.apps.PosPortalConfig',
    'students.apps.StudentsConfig',
    'sysadmin.apps.SysadminConfig',
    'moe_portal.apps.MoePortalConfig',
    #'netcoins.apps.NetcoinsConfig',
    'sch_portal.apps.SchPortalConfig',
    'ecoins_portal.apps.EcoinsPortalConfig',
    'discipline.apps.DisciplineConfig',
    'fileuploader.apps.FileuploaderConfig',
    'library.apps.LibraryConfig',
    'bursar_portal.apps.BursarPortalConfig',
    #'merchant_portal.apps.MerchantPortalConfig',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecoins.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecoins.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
				 'ENGINE': 'django.db.backends.postgresql',
				 'NAME': 'ecoins',
				 'HOST': 'localhost',
				 'USER': 'postgres',
				 'PASSWORD': 'postgres',
				 'PORT': '5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/home/e-coins/stuff/programming/django/workspace/ecoins/static',
]
#https://docs.djangoproject.com/en/1.9/ref/settings/
MEDIA_ROOT = '/home/e-coins/stuff/programming/django/workspace/ecoins/media/'
MEDIA_URL = '/media/'
