# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sysadmin', '0001_initial'),
        ('smsgateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentPhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Parent/Guardian Contacts',
            },
        ),
        migrations.CreateModel(
            name='StudentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryyear', models.CharField(max_length=5000, verbose_name='Entry year')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_category', to='school.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Student Category',
            },
        ),
        migrations.CreateModel(
            name='StudentClassStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Classes', verbose_name='Classes')),
                ('entryyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentclassstream_entryyear', to='sysadmin.EntryYear', verbose_name='Entry year')),
                ('streams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Streams', verbose_name='Streams')),
            ],
            options={
                'verbose_name_plural': 'Student Class Stream',
            },
        ),
        migrations.CreateModel(
            name='StudentParent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name='First name')),
                ('secondname', models.CharField(blank=True, max_length=255, verbose_name='Second name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last name')),
                ('specialcases', models.TextField(blank=True, verbose_name='Special case description')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Gender', verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'Student Parent',
            },
        ),
        migrations.CreateModel(
            name='StudentProfiles',
            fields=[
                ('admno', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ADM No')),
                ('firstname', models.CharField(max_length=255, verbose_name='First name')),
                ('secondname', models.CharField(blank=True, max_length=255, verbose_name='Second name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last name')),
                ('specialcases', models.TextField(blank=True, verbose_name='Special case description')),
                ('current_stream', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='static/media/', verbose_name='Photo')),
                ('dateofbirth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('admissiondate', models.DateField(verbose_name='Admission Date')),
                ('residence', models.CharField(max_length=255, verbose_name='Residence/Estate')),
                ('lastschoolattended', models.CharField(default='None', max_length=255, verbose_name='Last school attended')),
                ('lastschooladdress', models.CharField(default='None', max_length=255, verbose_name='School address')),
                ('schooltransport', models.CharField(max_length=255, verbose_name='School address')),
                ('schoollunch', models.CharField(max_length=255, verbose_name='School lunch')),
                ('isactive', models.BooleanField(default=True, verbose_name='Active')),
                ('academic_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Category', verbose_name='Academic Category')),
                ('current_classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Classes', verbose_name='Current Classes')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentprofiles_gender', to='school.Gender', verbose_name='Gender')),
                ('name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentprofiles_username', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'ordering': ['admno'],
                'verbose_name_plural': 'Student profile',
            },
        ),
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('studentprofiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='Student Profile')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Subjects', verbose_name='Subjects')),
            ],
            options={
                'verbose_name_plural': 'Student Subject',
            },
        ),
        migrations.AddField(
            model_name='studentparent',
            name='studentprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='Staff Id'),
        ),
        migrations.AddField(
            model_name='studentparent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentparent_username', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='studentclassstream',
            name='studentprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='Staff Id'),
        ),
        migrations.AddField(
            model_name='studentcategory',
            name='studentprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='Staff Id'),
        ),
        migrations.AddField(
            model_name='parentphoneno',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentParent', verbose_name='Student parent'),
        ),
        migrations.AddField(
            model_name='parentphoneno',
            name='phoneno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsgateway.PhoneBook', verbose_name='Phone-no'),
        ),
    ]
