# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=5000)),
                ('division', models.CharField(max_length=5000)),
                ('constituency', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=5000)),
                ('sublocation', models.CharField(max_length=5000)),
                ('town', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name_plural': 'Student Location',
            },
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='current_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Streams', verbose_name='Current Streams'),
        ),
        migrations.AddField(
            model_name='studentlocation',
            name='studentprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='student Id'),
        ),
    ]
