# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20160823_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiles',
            name='academic_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.Category', verbose_name='Academic Category'),
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='admissiondate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Admission Date'),
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='schoollunch',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='School lunch'),
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='schooltransport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='School address'),
        ),
    ]
