# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-26 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20160823_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofiles',
            name='accountnumber',
            field=models.CharField(default='XXXX123232XXXX', max_length=10000),
        ),
        migrations.AddField(
            model_name='studentprofiles',
            name='encryped_acc_no',
            field=models.CharField(default='XXXX123232XXXX', max_length=10000),
        ),
        migrations.AddField(
            model_name='studentprofiles',
            name='expirerydate',
            field=models.DateField(default='2018-01-01', verbose_name='expirerydate'),
        ),
    ]
