# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20160826_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofiles',
            name='accountnumber',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='encryped_acc_no',
            field=models.CharField(max_length=10000),
        ),
    ]
