# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20160902_0058'),
        ('sysadmin', '0001_initial'),
        ('students', '0005_auto_20160902_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='YellowForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indexnumber', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(blank=True, max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('birthcert', models.CharField(max_length=255)),
                ('pupilsinclasseght', models.CharField(max_length=255)),
                ('lastposition', models.CharField(max_length=255)),
                ('lastmarks', models.CharField(max_length=255)),
                ('cocurricularevents', models.TextField()),
                ('headmasterapproval', models.CharField(max_length=255)),
                ('dateofapproval', models.CharField(max_length=255)),
                ('headmasterphone', models.CharField(max_length=255)),
                ('fax', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('parentfullnames', models.CharField(max_length=255)),
                ('maritalstatus', models.CharField(max_length=255)),
                ('parentdead', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('nationalid', models.CharField(max_length=255)),
                ('employment', models.CharField(max_length=255)),
                ('inbusiness', models.CharField(max_length=255)),
                ('hasland', models.CharField(max_length=255)),
                ('otherincomeoptions', models.CharField(max_length=255)),
                ('physicaladdress', models.CharField(max_length=255)),
                ('listallsiblings', models.TextField()),
                ('applicationinfo', models.TextField()),
                ('cirtifydate', models.CharField(max_length=255)),
                ('cirtifysigniture', models.CharField(max_length=255)),
                ('cirtifyname', models.CharField(max_length=255)),
                ('cirtifyoccupation', models.CharField(max_length=255)),
                ('cirtifyaddress', models.CharField(max_length=255)),
                ('cirtifyfax', models.CharField(max_length=255)),
                ('cirtifyphone', models.CharField(max_length=255)),
                ('cirtifyemail', models.CharField(max_length=255)),
                ('freefullnames', models.CharField(max_length=255)),
                ('freesignature', models.CharField(max_length=255)),
                ('freephoneno', models.CharField(max_length=255)),
                ('recomenderfullnames', models.CharField(max_length=255)),
                ('recomendersignature', models.CharField(max_length=255)),
                ('recomenderoffice', models.CharField(max_length=255)),
                ('recomenderphoneno', models.CharField(max_length=255)),
                ('entryyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentclassstream_entryyear1', to='sysadmin.EntryYear', verbose_name='Entry year')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentprofiles_gender', to='school.Gender', verbose_name='Gender')),
                ('name', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name')),
                ('parentgender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentprofiles_gender1', to='school.Gender', verbose_name='Gender')),
            ],
            options={
                'verbose_name_plural': 'YellowForm',
            },
        ),
        migrations.AlterField(
            model_name='studentparent',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentprofiles_gender3', to='school.Gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='studentprofiles',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_studentprofiles_gender4', to='school.Gender', verbose_name='Gender'),
        ),
    ]
