# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20160925_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='yellowform',
            name='kcpeeng',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yellowform',
            name='kcpekisw',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yellowform',
            name='kcpemath',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yellowform',
            name='kcpesci',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yellowform',
            name='kcpess',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='yellowform',
            name='kcpetotal',
            field=models.CharField(default='', max_length=255),
        ),
    ]
