# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20160902_0058'),
        ('students', '0007_auto_20160925_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDormitory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateField(default=django.utils.timezone.now, verbose_name='Admission Date')),
                ('dormitory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Dormitory', verbose_name='student Id')),
                ('studentprofiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='student Id')),
            ],
            options={
                'verbose_name_plural': 'Student Location',
            },
        ),
    ]
