# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-25 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentdormitory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=5000)),
                ('studentprofiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='student Id')),
            ],
            options={
                'verbose_name_plural': 'Student Location',
            },
        ),
        migrations.CreateModel(
            name='StudentSports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=5000)),
                ('studentprofiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='student Id')),
            ],
            options={
                'verbose_name_plural': 'Student Location',
            },
        ),
    ]
