# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 04:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_holidayjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSupplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply', models.CharField(max_length=5000)),
                ('studentprofiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='Student Profile')),
            ],
            options={
                'verbose_name_plural': 'Student Category',
            },
        ),
    ]
