# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-27 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentsupplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsupplies',
            name='category',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
