# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 11:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smsgateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPhoneNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smsgateway.PhoneBook', verbose_name='Phone-no')),
            ],
            options={
                'verbose_name_plural': 'Staff Contacts',
            },
        ),
        migrations.CreateModel(
            name='StaffProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalid', models.IntegerField(default='00000000', verbose_name='National Id')),
                ('staff_code', models.IntegerField(default='000')),
                ('firstname', models.CharField(max_length=255, verbose_name='First name')),
                ('secondname', models.CharField(max_length=255, verbose_name='Second name')),
                ('lastname', models.CharField(max_length=255, verbose_name='Last name')),
                ('gender', models.CharField(max_length=255)),
                ('specialcases', models.TextField(blank=True, verbose_name='Special case description')),
                ('photo', models.ImageField(blank=True, upload_to='static/media/', verbose_name='Photo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolProfiles', verbose_name='Name')),
                ('username', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Staff Profile',
            },
        ),
        migrations.AddField(
            model_name='staffphoneno',
            name='staffprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.StaffProfiles', verbose_name='Staff profiles'),
        ),
    ]
