# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20160820_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='categorytype',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='classstreams',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dormitory',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='months',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='paymentmethods',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='schooltype',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='streams',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='terms',
            name='owner',
        ),
    ]
