# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20160820_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='streams',
            unique_together=set([]),
        ),
    ]
