# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-24 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20160824_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_gender', to='sysadmin.Gender', verbose_name='Gender'),
        ),
    ]
