# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20160824_1339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolaccounts',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='schoolaccounts',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='schoolemails',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='schoolemails',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoollocation',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='schoolphone',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='schoolphone',
            name='name',
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='accountnumber',
            field=models.CharField(default='21234567890987', max_length=10000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='constituency',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='division',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='email',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='encryped_acc_no',
            field=models.CharField(default='XXXX456789XXXX', max_length=10000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='expirerydate',
            field=models.DateField(default='2018-01-01', verbose_name='expirerydate'),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='location',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='phonenumber',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='sublocation',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='town',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='schoolprofiles',
            name='county',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.DeleteModel(
            name='SchoolAccounts',
        ),
        migrations.DeleteModel(
            name='SchoolEmails',
        ),
        migrations.DeleteModel(
            name='SchoolLocation',
        ),
        migrations.DeleteModel(
            name='SchoolPhone',
        ),
    ]
