# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20160902_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofiles',
            old_name='balance',
            new_name='pocketmoneybalance',
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='savingsbalance',
            field=models.CharField(default='1', max_length=5000),
        ),
        migrations.AddField(
            model_name='schoolprofiles',
            name='schfeesbalance',
            field=models.CharField(default='1', max_length=5000),
        ),
    ]
