# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 05:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discipline', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecases',
            name='studentprofiles',
            field=models.ForeignKey(default='201601', on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles', verbose_name='ADM No'),
        ),
    ]
