# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0002_disciplinecases_studentprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecases',
            name='blacklist',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='disciplinecases',
            name='blacklistdate',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='disciplinecases',
            name='studentprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles'),
        ),
        migrations.AlterField(
            model_name='disciplinecases',
            name='whitelist',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='disciplinecases',
            name='whitelistdate',
            field=models.CharField(max_length=10000),
        ),
    ]
