# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_auto_20160926_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecases',
            name='category',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
