# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-20 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netcoins', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccounts',
            name='studentprofiles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.StudentProfiles'),
        ),
    ]
